apiVersion: v2
name: user-api-gateway
description: Helm chart for user-api-gateway
type: application
version: 0.1.0
dependencies:
  - name: bhaiychalo-base
    version: "0.1.0"
    repository: "file://../../base"
