apiVersion: v2
name: fare-service
description: Helm chart for fare-service
type: application
version: 0.1.0
dependencies:
  - name: bhaiychalo-base
    version: "0.1.0"
    repository: "file://../../base"
