apiVersion: v2
name: location-ingest-service
description: Helm chart for location-ingest-service
type: application
version: 0.1.0
dependencies:
  - name: bhaiychalo-base
    version: "0.1.0"
    repository: "file://../../base"
