apiVersion: v2
name: connection-manager-service
description: Helm chart for connection-manager-service
type: application
version: 0.1.0
dependencies:
  - name: bhaiychalo-base
    version: "0.1.0"
    repository: "file://../../base"
