apiVersion: v2
name: risk-scoring-service
description: Helm chart for risk-scoring-service
type: application
version: 0.1.0
dependencies:
  - name: bhaiychalo-base
    version: "0.1.0"
    repository: "file://../../base"
