apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-config
  labels:
    {{- include "base.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
